### ISSUE TITLE
Ability to get a ReadStream from a FileSystemFileHandle

### ISSUE THREAD

**Issue by srgraham** [WICG/file-system-access#157] opened 2020-02-25 18:42 UTC
I want to open a stream to a file handle, so that as more content shows up in the file, the new content streams to the browser. Currently it looks like the only way to do this is refetch `FileSystemFileHandle.getFile()` and check if the size changed inside a loop, then reading everything in full again if so. I don't think this will be adequate for big files.

The use case for this is a `tail -f` look-a-like for the browser with various processing and display of the log contents as it comes in.

**Comment by jimmywarting** [comment] 2020-03-10 10:17
feels like a duplex read/write stream is in order?
Have been thinking about it also. just like the [seek method on writable stream](https://github.com/WICG/native-file-system/issues/19#issuecomment-490514791) i wish it did exist on some readable stream as well.

for stuff where you have to read part of the file. again and again

**Comment by mkruisselbrink** [comment] 2020-04-09 18:14
You don't have to read everything in full after the file changes (since `File` does support random-access reading by slicing etc). But the polling solution is still not ideal since if the file changes in between calling `getFile()` and you actually trying to read from it the read operation fails. So if the file updates frequently you might never be able to read from it.

So yeah, perhaps we should have an alternative way of reading from files that doesn't go through File/Blob objects, and thus doesn't have the limitations of those that they effectively represent snapshots of the file. If `tail -f` is the only use case for such an API, exposing it as a never-ending ReadableStream probably does make sense. There won't be any seeking in that case, but that is probably fine for that particular use case?

Are there other use cases where the snapshotting/invalidating-on-change behavior of Blob/File objects is problematic?

**Comment by tinchoz49** [comment] 2020-08-21 03:34
I wish we could have something like basic random access operations over a file without snapshots. Like `fs.read` and `fs.write` in node.js. Having to refetch the file after every write it gets us some performance issues in https://github.com/random-access-storage/random-access-chrome-file

**Comment by tomayac** [comment] 2020-08-21 07:34
> I wish we could have something like basic random access operations over a file without snapshots. Like `fs.read` and `fs.write` in node.js. Having to refetch the file after every write it gets us some performance issues in https://github.com/random-access-storage/random-access-chrome-file

@tinchoz49 I looked into this, and turns out you are not actually using the new Native File System API, but the [predecessor API](https://github.com/random-access-storage/random-access-chrome-file/blob/8f02ac6601ffd085f1d4760c0f76a382ea3b69d6/index.js#L4). You want to look at [`navigator.storage.getDirectory()`](https://wicg.github.io/native-file-system/#sandboxed-filesystem) instead, which currently in Chrome 86.0.4239.0 is still implemented as `self.getOriginPrivateDirectory()` (see https://github.com/WICG/native-file-system/pull/217 for the change). The switch to the new API should be painless. Please let us know if this solves the issue.

**Comment by xeonfusion** [comment] 2021-02-26 20:07
@mkruisselbrink posting this as suggested by @tomayac:

I have tried using either FileReader API or fetch method (used with blob URL created by createObjectURL()) to read a (.csv) file from local storage, that is being updated frequently by another process (a vital signs text stream being appended to the CSV file at a set time interval). The FileHandle was obtained from the standard <input> file picker. 

Both methods report errors similar to above issue about not being able to read the file due to net::ERR_UPLOAD_FILE_CHANGED or file has been modified error.

Reference to these reports: [https://stackoverflow.com/questions/61916331/re-uploading-a-file-with-ajax-after-it-was-changed-causes-neterr-upload-file-c](url),  [https://bugs.chromium.org/p/chromium/issues/detail?id=1084880&q=ERR_UPLOAD_FILE_CHANGED&can=2](url) etc

My code is at [https://github.com/xeonfusion/VSChart/blob/master/src/anaesthchart.jsx#L376](url)

The use of File.slice().arrayBuffer() Promise doesn't work either and can't access the file being modified.

There should be a way to read file updates efficiently rather than have just snapshots of the blob, such as the desired functionality of web apps, reading log files that are being updated in real time. The blob will be read only if the <input> file picker is used to select the file again after another process releases the file in use. Do let us know of any workarounds or alternative approaches.

**Comment by jimmywarting** [comment] 2021-02-26 22:39
@xeonfusion There is one other way that you can get a file handle from which you can retrieve a new File and call `.arrayBuffer()` without relying on chromes experimental file system access with requestPermission calls and that works in other browser right now. But `<input type=file>` is not one of them.

I'm talking about drag and drop
The idea is to get a file entry first from where you later can call the `.file()` function

`ondrop = evt => evt.dataTransfer.items[0].webkitGetAsEntry().file()`

```js
function drop(event) {
  event.stopPropagation();
  event.preventDefault();
    
  // get the file as an fileEntry (aka file handle)
  const fileEntry = event.dataTransfer.items[0].webkitGetAsEntry()
  let lastModificationTime = new Date(0)
  
  async function read (file) {
    // use the new async read method on blobs.
    console.log(await file.text())
  }
  
  function compare (meta) {
    if (meta.modificationTime > lastModificationTime) {
      lastModificationTime = meta.modificationTime
      fileEntry.file(read)
    }
  }
  
  setInterval(fileEntry.getMetadata.bind(fileEntry, compare), 1000)
}
```
more Demo/Code/explanation on my [SO answer](https://stackoverflow.com/a/62094037/1008999) about monitoring file changes

**Comment by xeonfusion** [comment] 2021-02-27 14:29
@jimmywarting @tomayac  I can confirm that the drag and drop method of obtaining a File handle, does work with a file being updated by another process continuously, without the file being modified error (or need to select the file handle again)!

The fileEntry is ontained similar to the drop event implementation described by you above:

```
  event.stopPropagation();
  event.preventDefault();
    
  // get the file as an fileEntry (aka file handle)
  const fileEntry = event.dataTransfer.items[0].webkitGetAsEntry()
```
Then a callback function can be used to read the data from the FileSystemFileEntry File() object as described here: [https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/file](url)

```
function ReadFile(entry, successCallback, errorCallback) {
        entry.file(function(file) {
          let reader = new FileReader();
      
          reader.onload = function() {
            successCallback(reader.result);
          };
      
          reader.onerror = function() {
            errorCallback(reader.error);
          }
      
          reader.readAsText(file);
        }, errorCallback);
      }

```

If drag and drop can work, then the input file dialog FileHandle behavior should be fixed to achieve the same functionality.

**Comment by jimmywarting** [comment] 2021-02-27 16:24
> If drag and drop can work, then the input file dialog FileHandle behavior should be fixed to achieve the same functionality.

Now we have gotten a little bit of track from the main topic and starts to be irrelevant.

But i just want to say that there is one other behavior change that you can do to `<input type=file>` and that is to selecting a directory. But this have some performances disadvantages since it walks over all folder and append each file into `input.files[]` as a flat list and makes the browser hang for a bit. and you don't get any folders only the prefixed relative path.
unfortunately this isn't a file or directory Entry either 

I do agree with you that it could have been nice to get a all files and directory as a Entry instead. but i guess it is not as easy to just add support for entries on the `<input type=files>`. it plays another roll that it also have to work together with the serialization of FormData, xhr, fetch, `<form>`... This may also mean that it has to be sync since it also have to add a content-length header? Supporting Entries on `<input type=files>` also means we have to update support on other parts of the web that use file inputs as well

what would you get if file input was async and you could get the files as an Entry instead?

```html
<form>
  <input type="file" name="upload" onchange="foo(event)" x-as-entry>
  <script>
    window.foo(evt) {
      new FormData(evt.target.form).get('upload') === ???
    }
  </script>
</form>
```

it would be cool idea doe if FormData could have some async behavior added to it so it could upload a FileSystemDirectoryHandle to the server. but for now the best way to upload them is either to zip everything and upload one file or manually craft a multipart FormData ReadableStream with streamable uploads
```js
const rs = new ReadableStream({
  pull(ctrl) {
    // enqueue one entry/handle
  }
})

const req = new Request(url, { 
  body: rs, 
  method: 'post',
  headers: { 'content-type': 'application/formdata-multipart' } 
})

fetch(req)
```
But not many browser supports streamable uploads today :( 

Maybe the file system access should invent a new form element that can map to showDirectoryPicker or showOpenFilePicker?

**Comment by ftreesmilo** [comment] 2021-07-18 19:43
similar to #72

**Comment by mkruisselbrink** [comment] 2021-07-20 20:22
Not sure how related this is to #72. Some of the work on access handles (#310) might be able to address some of these us cases, although that is currently planned to be limited to files in the origin private file system. Not sure if we can come up with a solution where we could use a similar API for read-only access to arbitrary files, but there might be something we can come up with...

**Comment by a-sully** [comment] 2022-02-11 21:41
Closing this issue since this seems mostly addressed by the new Access Handle surface within the Origin Private File System https://github.com/WICG/file-system-access/pull/344. If you have a more specific feature request which isn't addressed by Access Handles, feel free to open a new issue :)

**Closed by a-sully** 2022-02-11 21:41 UTC
Labels: enhancement
