### ISSUE TITLE
send a handle to a sandboxed iframe

### ISSUE THREAD

**Issue by jimmywarting** [WICG/file-system-access#281] opened 2021-02-22 19:31 UTC
I'm having problem transferering a sub directory handle to a sandboxed iframe 
`<iframe hidden src="/vm.html" sandbox="allow-scripts">`.
`contentWindow.postMessage(handle, '*')`

it works if i send it within my own web workers or other tabs but not otherwise.
`self.postMessage(handle)`
Is there some limitation that don't allow another origin access to a handle if i wanted to share a subfolder?
I have tried creating a MessageChannel and send it over that way also but it did not work either.

I can't set `contentWindow.subfolder = handle` since it is sandboxed
i wish i could but i can't.
I'm trying not to give the `"vm"` the root directory,  only a subfolder of it.
so i don't want to add the allow-same-origin cuz then the VM could have access to the root handle that have been saved in indexeddb

is there some way around this, i have heard about Realms... perhaps it would be better but no browser have implemented it.

**Comment by mkruisselbrink** [comment] 2021-02-23 17:45
Currently this is working as intended. You can only postMessage a handle to a context that is same origin with the original context. This was primarily done to keep the permission model/UI implications simple to reason about initially. As such I can certainly see a future where we'd loosen this requirement (after all, you could proxy operations over a MessageChannel anyway, allowing arbitrary message target to operate on files/directories without actually transferring the handles themselves).

Also somewhat related to #245

**Comment by jimmywarting** [comment] 2021-02-23 23:14
> This was primarily done to keep the permission model/UI implications simple to reason about initially.

I can see why that is... I'm currently doing some low level of postMessage back and forth but it's annoying to put it mildy. 
I have looked into something like web-worker-proxy and comlink that basically use proxies so you can call it like normally but you would have the object living in another thread (worker). But it would have been a lot nicer to just share the handle with another origin

In my case i use hidden iframes to run third party code - so having a permission UI model with no user interaction would not work
if i somehow could manage the permission policy myself where i already have readwrite access then i could decide what permission the other origin should have.

I could imagine a thing where you would be able to copy a handle with a new permission and then share it
```js
btn.onclick = () => {
  const myHandle = await handle.requestPermission({ mode: 'readwrite' })
  const newHandle = myHandle.clone({ mode: 'read' })
  postMessage(newHandle, targetOrigin)
}
```
maybe even be able to specify what other origin it should be work for
`myHandle.clone({ mode: 'read', origin: 'https://other.domain' })`
kind of how you can specify what targetOrigin a postMessage should work for. but in my case i would need `*` since my sandboxed iframe don't have a origin

**Comment by mkruisselbrink** [comment] 2022-02-11 22:00
Closing this in favor of #245, although permission policy integration might not fully address the desire to give less access to handles than the main page has.

**Closed by mkruisselbrink** 2022-02-11 22:00 UTC
