### ISSUE TITLE
Issue management of the project

### ISSUE THREAD

**Issue by ftreesmilo** [WICG/file-system-access#311] opened 2021-07-03 16:37 UTC
Is the intent to leave all issues open?

It looks like there are now quite a few issues here all requesting common things. (persistent permissions is one example)
Some issues requesting help (which was provided and is no longer relevant)

@tomayac  Do you want some help managing the issues?

**Comment by tomayac** [comment] 2021-07-03 23:06
(I don’t _manage_ the issues queue, just read and occasionally respond.)

**Comment by inexorabletash** [comment] 2021-07-07 17:04
Since we're all busy, comments on bugs ("Can this be closed?", "Is this a duplicate of XYZ?") would be appreciated. Thanks for offering!

**Closed** 2021-07-18 19:50 UTC
