### ISSUE TITLE
Using showDirectoryPicker from Chrome extension fails

### ISSUE THREAD

**Issue by antonsimola** [WICG/file-system-access#314] opened 2021-07-18 09:50 UTC
I'm trying to use directory picker from a chrome extension. File picker seems to work, but when I try to pick a directory I get:

`core.js:6210 ERROR Error: Uncaught (in promise): AbortError: The user aborted a request.
Error: The user aborted a request.`

![image](https://user-images.githubusercontent.com/8913934/126062562-39358e9a-6eba-4b93-a181-f14d15511745.png).

Code (I was also trying with browser-fs-access polyfill, same result):

```typescript
     // import * as fs from 'browser-fs-access';
    const files =  await fs.fileOpen({multiple:true});
    console.log(files);
    const fileHandles = await window.showOpenFilePicker({multiple:true});
    console.log(fileHandles);

    const directoryHandle = await window.showDirectoryPicker();
    console.log(directoryHandle);

    const fsDirectoryHandle = await fs.directoryOpen();
    console.log(fsDirectoryHandle);
```
Maybe I'm doing something wrong, or it's some issue with extensions specifically?

**Comment by ftreesmilo** [comment] 2021-07-18 19:34
Is this a duplicate of #289 ?

**Comment by mkruisselbrink** [comment] 2021-07-20 20:37
Could you file an issue on crbug.com/new, ideally with a sample extension that repros the issue? I don't think this is a spec issue, so clothing this bug here.

**Closed by mkruisselbrink** 2021-07-20 20:37 UTC

**Comment by dragonman225** [comment] 2022-11-24 12:23
I'm encountering the same problem, `window.showDirectoryPicker()` doesn't work in a Chrome extension and would make it unresponsive. I think it may be that either there's a bug in Chrome or Chrome decides to not allow using the API in a Chrome extension. @antonsimola were you able to find a workaround?
